"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Check, Copy, LoaderCircle, LockKeyhole } from "lucide-react";

type Payment = { chargeId: string; status: string; amountCents?: number; payment: { pixCode: string | null; qrCode: string | null; expiresAt: string | null } };

export default function CheckoutPage() {
  const [form, setForm] = useState({ name: "", email: "", document: "", phone: "", accepted: false });
  const [payment, setPayment] = useState<Payment | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const idempotency = useRef(crypto.randomUUID());
  useEffect(() => { void fetch("/api/account/profile", { cache: "no-store" }).then(async (r) => { if (r.status === 401) { location.assign(`/login?next=${encodeURIComponent("/checkout")}`); return; } const data = await r.json(); if (data.profile) setForm((v) => ({ ...v, name: data.profile.full_name ?? "", email: data.profile.email ?? "", phone: data.profile.phone ?? "" })); }); }, []);
  useEffect(() => { if (!payment?.chargeId || ["active", "cancelled", "expired", "failed"].includes(payment.status)) return; const timer = setInterval(() => { void fetch(`/api/billing/charges/${payment.chargeId}`, { cache: "no-store" }).then((r) => r.json()).then((result) => { if (result.data) { setPayment((current) => current ? { ...current, status: result.data.subscriptionStatus, payment: result.data.payment } : current); if (result.data.subscriptionStatus === "active") setMessage("Pagamento confirmado. Sua assinatura está ativa."); } }); }, 4000); return () => clearInterval(timer); }, [payment?.chargeId, payment?.status]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); const response = await fetch("/api/billing/checkout", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": idempotency.current }, body: JSON.stringify({ planSlug: "prisma-completo", acceptedTerms: form.accepted, customer: { name: form.name, email: form.email, document: form.document, phone: form.phone } }) }); const result = await response.json(); setLoading(false); if (!response.ok) { setMessage(result.error?.message ?? "Não foi possível gerar o PIX."); return; } setPayment({ chargeId: result.data.chargeId, status: result.data.status, amountCents: result.data.amountCents, payment: result.data.payment }); }
  const qr = payment?.payment.qrCode; const qrSrc = qr?.startsWith("data:image/") || qr?.startsWith("https://") ? qr : qr ? `data:image/png;base64,${qr}` : null;
  return <main className="min-h-dvh px-5 py-10 themeable-bg-page themeable-text-ink"><div className="mx-auto max-w-[980px]"><Link href="/" className="text-[14px] text-prisma-blue">← Voltar para o site</Link><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_390px]">
    <section className="rounded-[24px] border p-6 themeable-bg-canvas themeable-border-hairline sm:p-8"><p className="text-[13px] font-semibold uppercase tracking-[.13em] text-prisma-blue">Checkout seguro</p><h1 className="mt-2 text-[32px] font-semibold tracking-[-1px]">Prisma Completo</h1><p className="mt-2 text-[15px] themeable-text-ink-muted-48">Todas as funcionalidades, vídeos e plays sem limite artificial.</p><div className="my-6 flex items-baseline gap-2"><strong className="text-[44px] tracking-[-1.5px]">R$ 97</strong><span className="themeable-text-ink-muted-48">por mês</span></div><ul className="grid gap-3 text-[14px] sm:grid-cols-2">{["Player completo", "Analytics avançado", "Testes A/B", "Proteção de domínio", "Smart Autoplay", "Recursos futuros inclusos"].map((x) => <li key={x} className="flex gap-2"><Check size={17} className="text-prisma-blue" />{x}</li>)}</ul></section>
    <section className="rounded-[24px] border p-6 themeable-bg-canvas themeable-border-hairline">{payment ? <div><h2 className="text-[20px] font-semibold">Pague com PIX</h2><p className="mt-1 text-[13px] themeable-text-ink-muted-48">A confirmação acontece automaticamente.</p>{qrSrc && <Image unoptimized src={qrSrc} alt="QR Code PIX" width={208} height={208} className="mx-auto my-5 size-52 rounded-[14px] bg-white p-2" />}<div className="mt-5 rounded-[14px] border p-3 themeable-border-hairline"><p className="break-all text-[11px] themeable-text-ink-muted-48">{payment.payment.pixCode}</p></div><button onClick={() => void navigator.clipboard.writeText(payment.payment.pixCode ?? "")} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-full bg-prisma-blue text-[14px] font-semibold text-white"><Copy size={16} />Copiar código PIX</button><div className="mt-5 flex items-center gap-2 text-[13px] text-prisma-blue">{payment.status === "active" ? <Check size={17} /> : <LoaderCircle size={17} className="animate-spin" />}{payment.status === "active" ? "Assinatura ativa" : "Aguardando confirmação segura"}</div>{message && <p role="status" className="mt-3 text-[13px] text-green-600">{message}</p>}{payment.status === "active" && <Link href="/dashboard/videos" className="mt-4 block text-center text-[14px] text-prisma-blue">Ir para a dashboard →</Link>}</div> : <form onSubmit={submit} className="space-y-4"><h2 className="text-[20px] font-semibold">Dados do assinante</h2>{[["Nome completo","name","text"],["E-mail","email","email"],["CPF","document","text"],["Telefone com DDD","phone","tel"]].map(([label,key,type]) => <label key={key} className="block text-[13px] font-medium">{label}<input required type={type} value={form[key as keyof typeof form] as string} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1.5 h-11 w-full rounded-full border bg-transparent px-4 outline-none focus:border-prisma-blue themeable-border-hairline" /></label>)}<label className="flex gap-3 text-[12px] leading-5 themeable-text-ink-muted-48"><input type="checkbox" checked={form.accepted} onChange={(e) => setForm({ ...form, accepted: e.target.checked })} className="mt-1" />Li e aceito os Termos de Uso, a Política de Privacidade e a cobrança recorrente mensal de R$ 97.</label><button disabled={loading || !form.accepted} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-prisma-blue text-[14px] font-semibold text-white disabled:opacity-45">{loading && <LoaderCircle size={17} className="animate-spin" />}{loading ? "Gerando PIX…" : "Gerar PIX de R$ 97"}</button>{message && <p role="status" className="text-[13px] text-red-500">{message}</p>}<p className="flex items-center justify-center gap-2 text-[11px] themeable-text-ink-muted-48"><LockKeyhole size={13} />Credenciais e preço validados somente no servidor</p></form>}</section>
  </div></div></main>;
}
