"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, CreditCard, ShieldCheck } from "lucide-react";
import Header from "@/components/dashboard/Header";

type Subscription = { id: string; status: string; currentPeriodEnd: string | null; plan: { name: string; amount_cents: number; currency: string } };
const labels: Record<string, string> = { active: "Ativa", pending_first_payment: "Aguardando primeiro pagamento", creating: "Criando cobrança", past_due: "Pagamento em atraso", grace_period: "Período de tolerância", suspended: "Suspensa", cancelled: "Cancelada", failed: "Falha no checkout" };

export default function BillingPage() {
  const [subscription, setSubscription] = useState<Subscription | null | undefined>();
  useEffect(() => { void fetch("/api/billing/subscription", { cache: "no-store" }).then((r) => r.json()).then((x) => setSubscription(x.data ?? null)); }, []);
  return <><Header /><main className="dashboard-content flex-1"><h1 className="text-[28px] font-semibold tracking-[-.7px] themeable-text-ink">Plano e cobrança</h1><p className="mt-1 text-[14px] themeable-text-ink-muted-48">Gerencie o acesso financeiro da sua conta.</p><section className="mt-7 max-w-[720px] rounded-[22px] border p-6 themeable-bg-canvas themeable-border-hairline sm:p-8">{subscription === undefined ? <p className="text-[14px] themeable-text-ink-muted-48">Carregando assinatura…</p> : subscription ? <><div className="flex flex-wrap items-start justify-between gap-5"><div><span className="text-[12px] uppercase tracking-[.12em] text-prisma-blue">Plano atual</span><h2 className="mt-1 text-[22px] font-semibold themeable-text-ink">{subscription.plan.name}</h2><p className="mt-1 text-[14px] themeable-text-ink-muted-48">R$ {(subscription.plan.amount_cents / 100).toFixed(2).replace(".", ",")} por mês</p></div><span className="rounded-full bg-prisma-blue/10 px-4 py-2 text-[13px] font-medium text-prisma-blue">{labels[subscription.status] ?? subscription.status}</span></div><div className="my-6 h-px bg-black/10 dark:bg-white/10" /><div className="grid gap-3 sm:grid-cols-2"><Info icon={CheckCircle2} text="Todas as funcionalidades incluídas" /><Info icon={ShieldCheck} text="Pagamento processado pela SyncPay" /></div>{subscription.currentPeriodEnd && <p className="mt-6 text-[13px] themeable-text-ink-muted-48">Período atual até {new Date(subscription.currentPeriodEnd).toLocaleDateString("pt-BR")}.</p>}</> : <div className="text-center"><CreditCard className="mx-auto text-prisma-blue" /><h2 className="mt-4 text-[20px] font-semibold themeable-text-ink">Nenhuma assinatura ativa</h2><p className="mt-2 text-[14px] themeable-text-ink-muted-48">Assine o Prisma Completo por R$ 97/mês.</p><Link href="/checkout" className="mt-5 inline-flex min-h-11 items-center rounded-full bg-prisma-blue px-6 text-[14px] font-semibold text-white">Assinar agora</Link></div>}</section></main></>;
}
function Info({ icon: Icon, text }: { icon: typeof CheckCircle2; text: string }) { return <div className="flex gap-2 text-[13px] themeable-text-ink"><Icon size={17} className="text-prisma-blue" />{text}</div>; }
