import { Check, CreditCard, QrCode, Sparkles } from "lucide-react";
import Header from "@/components/dashboard/Header";
import CancelSubscriptionButton from "@/features/billing/components/CancelSubscriptionButton";
import CheckoutActions from "@/features/billing/components/CheckoutActions";
import AiCreditCheckoutButton from "@/features/billing/components/AiCreditCheckoutButton";
import { requireUser } from "@/lib/auth/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { formatBRL, sharedFeatures, type BillingPlan } from "@/lib/billing/catalog";
import { getAccountAccess } from "@/lib/access/service";
export const dynamic = "force-dynamic";
export default async function BillingPage() {
  const userId = await requireUser("/dashboard/billing"); const admin = createAdminClient();
  const [subscriptionResult, plansResult, creditsResult, walletResult, access] = await Promise.all([
    admin.from("subscriptions").select("status,billing_method,current_period_end,cancelled_at,plan:billing_plans(name,amount_cents)").eq("user_id", userId).maybeSingle(),
    admin.from("billing_plans").select("*").eq("is_active", true).order("display_order"),
    admin.from("ai_credit_products").select("*").eq("is_active", true).order("display_order"),
    admin.from("ai_credit_wallets").select("balance").eq("user_id", userId).maybeSingle(), getAccountAccess(userId),
  ]);
  const subscription = subscriptionResult.data; const plan = Array.isArray(subscription?.plan) ? subscription.plan[0] : subscription?.plan;
  return <><Header /><main className="dashboard-content"><div><h1 className="text-[28px] font-semibold tracking-[-.7px] themeable-text-ink">Plano e pagamentos</h1><p className="mt-1 text-[14px] themeable-text-ink-muted-48">Teste gratis, assinatura e creditos da Prisma IA em um so lugar.</p></div>
  <section className="mt-6 rounded-[20px] border p-5 themeable-bg-canvas themeable-border-hairline">{subscription?.status === "active" ? <div className="flex flex-wrap items-center justify-between gap-4"><div><span className="rounded-full bg-green-500/10 px-3 py-1 text-[11px] font-semibold uppercase text-green-600">Plano ativo</span><h2 className="mt-3 text-[22px] font-semibold themeable-text-ink">{plan?.name ?? "Plano Prisma"}</h2><p className="text-[13px] themeable-text-ink-muted-48">Valido ate {subscription.current_period_end ? new Date(subscription.current_period_end).toLocaleDateString("pt-BR") : "a proxima renovacao"}</p></div><div className="flex items-center gap-3"><span className="flex items-center gap-2 rounded-full themeable-bg-surface-pearl px-4 py-2 text-[13px] themeable-text-ink">{subscription.billing_method === "card" ? <CreditCard size={17} /> : <QrCode size={17} />}{subscription.billing_method === "card" ? "Cartao recorrente" : "Pix 30 dias"}</span>{subscription.billing_method === "card" && <CancelSubscriptionButton />}</div></div> : access.trialStatus === "active" ? <div><span className="rounded-full bg-prisma-blue/10 px-3 py-1 text-[11px] font-semibold text-prisma-blue">TESTE ATIVO</span><h2 className="mt-3 text-[22px] font-semibold themeable-text-ink">Acesso completo liberado</h2><p className="text-[13px] themeable-text-ink-muted-48">Seu teste termina em {access.trialEndsAt ? new Date(access.trialEndsAt).toLocaleDateString("pt-BR") : "14 dias"}. Nenhuma cobranca sera feita automaticamente.</p></div> : <div><h2 className="text-[20px] font-semibold themeable-text-ink">Escolha seu acesso</h2><p className="mt-1 text-[13px] themeable-text-ink-muted-48">Cartao renova automaticamente. Pix libera 30 dias sem renovacao.</p></div>}</section>
  <h2 className="mt-9 text-[21px] font-semibold themeable-text-ink">Planos Prisma</h2><div className="mt-4 grid gap-4 xl:grid-cols-3">{(plansResult.data as BillingPlan[] ?? []).map((item) => <article key={item.id} className={`rounded-[22px] border p-5 themeable-bg-canvas themeable-border-hairline ${item.is_featured ? "ring-2 ring-prisma-blue" : ""}`}><p className="text-[15px] font-semibold themeable-text-ink">{item.name}</p><p className="mt-2 text-[12px] leading-relaxed themeable-text-ink-muted-48">{item.description}</p><p className="mt-5 text-[30px] font-semibold themeable-text-ink">{formatBRL(item.amount_cents)}<span className="text-[12px] font-normal themeable-text-ink-muted-48">/mes</span></p><div className="mt-4 space-y-2">{sharedFeatures.slice(0,2).map((feature) => <p key={feature} className="flex gap-2 text-[12px] themeable-text-ink"><Check size={14} className="text-prisma-blue" />{feature}</p>)}</div><CheckoutActions plan={item.slug} /></article>)}</div>
  <div className="mt-10 flex items-end justify-between"><div><h2 className="flex items-center gap-2 text-[21px] font-semibold themeable-text-ink"><Sparkles size={20} className="text-prisma-blue" />Creditos Prisma IA</h2><p className="mt-1 text-[13px] themeable-text-ink-muted-48">Saldo atual: <strong className="text-prisma-blue">{walletResult.data?.balance ?? 0} creditos</strong>. Os creditos nao expiram.</p></div></div><div className="mt-4 grid gap-4 md:grid-cols-3">{(creditsResult.data ?? []).map((item) => <article key={item.id} className={`rounded-[20px] border p-5 themeable-bg-canvas themeable-border-hairline ${item.is_featured ? "ring-2 ring-prisma-blue" : ""}`}><p className="text-[15px] font-semibold themeable-text-ink">{item.name}</p><p className="mt-3 text-[26px] font-semibold themeable-text-ink">{item.credits + item.bonus_credits} <span className="text-[12px] font-normal themeable-text-ink-muted-48">creditos</span></p>{item.bonus_credits > 0 && <p className="text-[11px] font-semibold text-green-600">+{item.bonus_credits} de bonus incluidos</p>}<p className="mt-4 text-[19px] font-semibold themeable-text-ink">{formatBRL(item.amount_cents)}</p><AiCreditCheckoutButton product={item.slug} /></article>)}</div></main></>;
}
