import { NextResponse } from "next/server";

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) {
  const { id } = await context.params;
  if (!/^[0-9a-f-]{36}$/i.test(id)) return new NextResponse("/* Prisma Player: invalid id */", { status: 400, headers: { "content-type": "application/javascript; charset=utf-8" } });
  const script = `(()=>{const s=document.currentScript;const roots=[...document.querySelectorAll('[data-prisma-player="${id}"]')].filter(e=>!e.dataset.prismaMounted);for(const root of roots){root.dataset.prismaMounted='true';root.style.background='transparent';root.style.border='0';root.style.boxShadow='none';root.style.overflow='hidden';root.style.lineHeight='0';const mobile=root.dataset.mobilePlayer;const selected=mobile&&matchMedia('(max-width: 767px)').matches?mobile:'${id}';const mode=root.dataset.mode==='ab'?'/embed/ab/':'/embed/';const frame=document.createElement('iframe');frame.src=new URL(mode+selected,s.src).origin+mode+selected;frame.title=root.dataset.title||'Prisma Player';frame.loading=root.dataset.loading||'lazy';frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;frame.scrolling='no';frame.referrerPolicy='strict-origin-when-cross-origin';frame.style.cssText='position:absolute;inset:0;width:100%;height:100%;border:0;display:block;overflow:hidden;background:transparent;color-scheme:normal';addEventListener('message',event=>{if(event.source!==frame.contentWindow||event.data?.playerId!==selected)return;if(event.data?.type==='prisma-player:resize'){const height=Number(event.data.height);if(!Number.isFinite(height)||height<1)return;root.style.paddingTop='0';root.style.height=Math.ceil(height)+'px';return}if(event.data?.type!=='prisma-player:pixel-event')return;const d=event.data;const detail={video_id:d.videoId,player_id:d.playerId,progress_percent:Number(d.progressPercent)||0,pixel_name:String(d.pixelName||'')};window.dispatchEvent(new CustomEvent('prisma-player:event',{detail:{...detail,event_type:d.eventType,provider:d.provider}}));const provider=String(d.provider||'').toLowerCase();if(provider==='meta'&&typeof window.fbq==='function'){const names={impression:'ViewContent',play:'PrismaVideoPlay',progress:'PrismaVideoProgress',complete:'PrismaVideoComplete',cta_click:'Lead'};const name=names[d.eventType];if(name)window.fbq(name.startsWith('Prisma')?'trackCustom':'track',name,detail)}else if(provider==='google'&&typeof window.gtag==='function'){const names={impression:'view_item',play:'video_start',progress:'video_progress',complete:'video_complete',cta_click:'generate_lead'};const name=names[d.eventType];if(name)window.gtag('event',name,{...detail,send_to:String(d.pixelId||'')||undefined})}else if(provider==='tiktok'&&window.ttq&&typeof window.ttq.track==='function'){const names={impression:'ViewContent',play:'PrismaVideoPlay',progress:'PrismaVideoProgress',complete:'PrismaVideoComplete',cta_click:'ClickButton'};const name=names[d.eventType];if(name)window.ttq.track(name,detail)}},false);root.replaceChildren(frame)}})();`;
  return new NextResponse(script, { headers: {
    "content-type": "application/javascript; charset=utf-8",
    "cache-control": "public, max-age=0, must-revalidate",
    "access-control-allow-origin": "*",
    "cross-origin-resource-policy": "cross-origin",
    "x-content-type-options": "nosniff",
  } });
}
