"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Bell, Gift, LoaderCircle, Trash2 } from "lucide-react";

type Item = { id: string; title: string; message: string; action_label: string | null; action_url: string | null; read_at: string | null };

export default function InboxButton() {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [items, setItems] = useState<Item[]>([]);
  useEffect(() => { let active = true; void fetch("/api/account/inbox", { cache: "no-store" }).then((response) => response.json()).then((data) => { if (active) setItems(data?.items ?? []); }).catch(() => undefined).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function read(id: string) { await fetch("/api/account/inbox", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); setItems((current) => current.map((item) => item.id === id ? { ...item, read_at: new Date().toISOString() } : item)); }
  async function dismiss(id: string) { const response = await fetch("/api/account/inbox", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); if (response.ok) setItems((current) => current.filter((item) => item.id !== id)); }
  const unread = items.filter((item) => !item.read_at).length;
  return <div className="relative"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-label="Inbox" className="relative flex h-11 w-11 items-center justify-center rounded-full themeable-bg-surface-pearl themeable-text-ink-muted-48"><Bell size={16} />{unread > 0 && <span className="absolute right-0 top-0 flex h-5 min-w-5 items-center justify-center rounded-full bg-prisma-blue px-1 text-[10px] font-bold text-white">{unread}</span>}</button>{open && <div className="absolute right-0 top-[calc(100%+10px)] max-h-[440px] w-[min(380px,calc(100vw-24px))] overflow-y-auto rounded-[20px] border p-3 shadow-xl themeable-bg-canvas themeable-border-hairline"><div className="flex items-center justify-between px-2 py-1"><p className="text-[15px] font-semibold themeable-text-ink">Inbox Prisma</p><span className="text-[11px] themeable-text-ink-muted-48">{unread} novas</span></div>{loading ? <LoaderCircle className="mx-auto my-8 animate-spin text-prisma-blue" /> : items.length === 0 ? <p className="p-5 text-center text-[13px] themeable-text-ink-muted-48">Tudo tranquilo por aqui.</p> : <div className="mt-2 space-y-2">{items.map((item) => <article key={item.id} className={`rounded-[15px] p-4 ${item.read_at ? "themeable-bg-surface-pearl" : "border border-prisma-blue/25 bg-prisma-blue/5"}`}><div className="flex gap-3"><Gift size={18} className="mt-0.5 shrink-0 text-prisma-blue" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="text-[13px] font-semibold themeable-text-ink">{item.title}</p><button type="button" onClick={() => void dismiss(item.id)} aria-label="Excluir mensagem" className="grid h-7 w-7 shrink-0 place-items-center rounded-full hover:bg-red-500/10 hover:text-red-500"><Trash2 size={14} /></button></div><p className="mt-1 text-[12px] leading-relaxed themeable-text-ink-muted-48">{item.message}</p>{item.action_url && <Link href={item.action_url} onClick={() => void read(item.id)} className="mt-3 inline-flex text-[12px] font-semibold text-prisma-blue">{item.action_label || "Abrir"}</Link>}</div></div></article>)}</div>}</div>}</div>;
}
