"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowLeft, BarChart3, Download, Funnel, Globe2, Lightbulb, MonitorSmartphone, Radio, RefreshCw, Users } from "lucide-react";
import Link from "next/link";

type Summary = { impressions: number; plays: number; playRate: number; reached25: number; reached50: number; reached75: number; reached90: number; completed: number; completionRate: number; ctaClicks: number; conversions: number };
type Point = { point: number; viewers: number; rate: number };
type Dimension = { name: string; impressions: number; plays: number; playRate: number; completes: number; completionRate: number };
type Data = { video: { title: string; duration_seconds: number | null }; summary: Summary; retention: Point[]; funnel: { name: string; value: number }[]; dimensions: Record<string, Dimension[]>; insights: { tone: string; title: string; detail: string }[]; live: number };
const tabs = [{ id: "overview", label: "Visão geral", icon: BarChart3 }, { id: "retention", label: "Retenção", icon: Activity }, { id: "funnel", label: "Funil", icon: Funnel }, { id: "audience", label: "Público", icon: Globe2 }, { id: "technology", label: "Tecnologia", icon: MonitorSmartphone }, { id: "traffic", label: "Origem", icon: Users }, { id: "live", label: "Ao vivo", icon: Radio }];

function format(value: number, percent = false) { return percent ? `${value.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%` : value.toLocaleString("pt-BR"); }

function DimensionTable({ title, rows }: { title: string; rows: Dimension[] }) {
  return <section className="rounded-[20px] border p-5 themeable-bg-canvas themeable-border-hairline"><h3 className="text-[17px] font-semibold themeable-text-ink">{title}</h3>{rows.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[13px]"><thead className="themeable-text-ink-muted-48"><tr><th className="pb-3 font-medium">Segmento</th><th>Visualizações</th><th>Plays</th><th>Play rate</th><th>Conclusões</th><th>Retenção final</th></tr></thead><tbody>{rows.map((row) => <tr key={row.name} className="border-t themeable-border-hairline"><td className="py-3 font-semibold themeable-text-ink">{row.name}</td><td>{format(row.impressions)}</td><td>{format(row.plays)}</td><td>{format(row.playRate, true)}</td><td>{format(row.completes)}</td><td>{format(row.completionRate, true)}</td></tr>)}</tbody></table></div> : <p className="mt-8 pb-5 text-center text-[14px] themeable-text-ink-muted-48">Os segmentos aparecerão quando o embed receber acessos.</p>}</section>;
}

export default function AnalyticsWorkspace({ videoId }: { videoId: string }) {
  const [data, setData] = useState<Data | null>(null), [tab, setTab] = useState("overview"), [days, setDays] = useState(30), [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); const response = await fetch(`/api/analytics/${videoId}?days=${days}`, { cache: "no-store" }); if (response.ok) setData(await response.json()); setLoading(false); }, [days, videoId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const maxFunnel = data?.funnel[0]?.value || 1;
  const exportCsv = () => { if (!data) return; const rows = [["Métrica", "Valor"], ...Object.entries(data.summary).map(([key, value]) => [key, String(value)])]; const blob = new Blob([rows.map((row) => row.join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = `prisma-analytics-${videoId}.csv`; anchor.click(); URL.revokeObjectURL(href); };
  const cards = useMemo(() => data ? [{ label: "Visualizações", value: format(data.summary.impressions), hint: "Sessões que viram o player" }, { label: "Plays", value: format(data.summary.plays), hint: "Pessoas que iniciaram" }, { label: "Play rate", value: format(data.summary.playRate, true), hint: "Plays ÷ visualizações" }, { label: "Chegaram à oferta", value: format(data.summary.reached75), hint: "Assistiram pelo menos 75%" }, { label: "Conclusões", value: format(data.summary.completed), hint: "Chegaram ao fim" }, { label: "Retenção final", value: format(data.summary.completionRate, true), hint: "Conclusões ÷ plays" }] : [], [data]);
  return <main className="min-h-dvh themeable-bg-page"><header className="sticky top-0 z-20 flex min-h-16 items-center justify-between gap-3 border-b px-4 backdrop-blur-xl themeable-bg-page themeable-border-hairline sm:px-7"><div className="min-w-0"><Link href="/dashboard/videos" className="flex items-center gap-2 text-[13px] text-prisma-blue"><ArrowLeft size={15} />Voltar aos vídeos</Link><h1 className="mt-1 truncate text-[18px] font-semibold themeable-text-ink">{data?.video.title ?? "Analytics da VSL"}</h1></div><div className="flex items-center gap-2"><select value={days} onChange={(event) => setDays(Number(event.target.value))} className="h-10 rounded-full border bg-transparent px-3 text-[13px] themeable-border-hairline themeable-text-ink"><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={365}>1 ano</option></select><button onClick={() => void load()} aria-label="Atualizar" className="grid h-10 w-10 place-items-center rounded-full border themeable-border-hairline themeable-text-ink"><RefreshCw size={16} className={loading ? "animate-spin" : ""} /></button><button onClick={exportCsv} className="hidden h-10 items-center gap-2 rounded-full border px-4 text-[13px] themeable-border-hairline themeable-text-ink sm:flex"><Download size={15} />CSV</button></div></header>
    <div className="mx-auto grid max-w-[1500px] gap-5 p-4 lg:grid-cols-[220px_minmax(0,1fr)] lg:p-7"><nav className="h-fit rounded-[20px] border p-2 themeable-bg-canvas themeable-border-hairline lg:sticky lg:top-24">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`flex min-h-11 w-full items-center gap-3 rounded-[14px] px-3 text-left text-[14px] transition ${tab === item.id ? "bg-prisma-blue text-white" : "themeable-text-ink hover:bg-prisma-blue/10"}`}><Icon size={17} />{item.label}</button>; })}</nav>
      <div className="min-w-0">{loading && !data ? <div className="grid min-h-[460px] place-items-center"><RefreshCw className="animate-spin text-prisma-blue" /></div> : !data ? <div className="rounded-[20px] border p-10 text-center themeable-bg-canvas themeable-border-hairline themeable-text-ink">Não foi possível carregar os dados. Confira se a migration de Analytics foi aplicada.</div> : <>
        {tab === "overview" && <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map((card) => <article key={card.label} className="rounded-[20px] border p-5 themeable-bg-canvas themeable-border-hairline"><p className="text-[13px] themeable-text-ink-muted-48">{card.label}</p><strong className="mt-2 block text-[28px] tracking-tight themeable-text-ink">{card.value}</strong><p className="mt-1 text-[12px] themeable-text-ink-muted-48">{card.hint}</p></article>)}</section><section className="rounded-[20px] border p-5 themeable-bg-canvas themeable-border-hairline"><div className="flex items-center gap-2"><Lightbulb size={18} className="text-amber-500" /><h2 className="font-semibold themeable-text-ink">Diagnóstico inteligente</h2></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{data.insights.map((insight) => <article key={insight.title} className="rounded-[15px] bg-prisma-blue/7 p-4"><strong className="themeable-text-ink">{insight.title}</strong><p className="mt-1 text-[13px] leading-relaxed themeable-text-ink-muted-48">{insight.detail}</p></article>)}</div></section></div>}
        {tab === "retention" && <section className="rounded-[20px] border p-5 themeable-bg-canvas themeable-border-hairline"><h2 className="text-[18px] font-semibold themeable-text-ink">Curva de retenção</h2><p className="mt-1 text-[13px] themeable-text-ink-muted-48">Mostra quantas pessoas permanecem em cada trecho. Os dados são marcos reais enviados pelo player.</p><div className="mt-8 flex h-[330px] items-end gap-2 border-b border-l px-3 themeable-border-hairline">{data.retention.map((point) => <div key={point.point} className="flex h-full flex-1 flex-col justify-end gap-2"><span className="text-center text-[11px] font-semibold themeable-text-ink">{format(point.rate, true)}</span><div className="min-h-1 rounded-t-[10px] bg-gradient-to-t from-prisma-blue to-cyan-400 transition-all" style={{ height: `${Math.max(2, point.rate)}%` }} /><span className="pb-2 text-center text-[11px] themeable-text-ink-muted-48">{point.point}%</span></div>)}</div></section>}
        {tab === "funnel" && <section className="rounded-[20px] border p-5 themeable-bg-canvas themeable-border-hairline"><h2 className="text-[18px] font-semibold themeable-text-ink">Funil da VSL</h2><div className="mt-7 space-y-3">{data.funnel.map((step, index) => <div key={step.name} className="grid grid-cols-[120px_1fr_70px] items-center gap-3 text-[13px]"><span className="themeable-text-ink">{step.name}</span><div className="h-10 overflow-hidden rounded-[12px] bg-prisma-blue/8"><div className="h-full rounded-[12px] bg-prisma-blue transition-all" style={{ width: `${Math.max(step.value ? 5 : 0, step.value / maxFunnel * 100)}%`, opacity: 1 - index * .08 }} /></div><strong className="text-right themeable-text-ink">{format(step.value)}</strong></div>)}</div></section>}
        {tab === "audience" && <div className="grid gap-5"><DimensionTable title="Países" rows={data.dimensions.countries} /><DimensionTable title="Dispositivos" rows={data.dimensions.devices} /></div>}
        {tab === "technology" && <div className="grid gap-5"><DimensionTable title="Sistemas operacionais" rows={data.dimensions.operatingSystems} /><DimensionTable title="Navegadores" rows={data.dimensions.browsers} /></div>}
        {tab === "traffic" && <DimensionTable title="Origem do tráfego" rows={data.dimensions.traffic} />}
        {tab === "live" && <section className="grid min-h-[500px] place-items-center rounded-[20px] border p-8 text-center themeable-bg-canvas themeable-border-hairline"><div><span className="relative mx-auto grid h-24 w-24 place-items-center rounded-full bg-prisma-blue/10"><Radio size={38} className="text-prisma-blue" /><i className="absolute right-2 top-2 h-4 w-4 animate-pulse rounded-full bg-red-500" /></span><strong className="mt-6 block text-[52px] tracking-tight themeable-text-ink">{data.live}</strong><p className="themeable-text-ink-muted-48">espectador{data.live === 1 ? "" : "es"} ativo{data.live === 1 ? "" : "s"} nos últimos 2 minutos</p></div></section>}
      </>}</div></div></main>;
}
