"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Bell, CheckCircle2, ChevronRight, CircleUserRound, CreditCard, Database, HardDrive, KeyRound, Lock, Play, Shield, Smartphone, Sparkles, User } from "lucide-react";
import Header from "@/components/dashboard/Header";
import { createClient } from "@/lib/supabase/client";

type Tab = "overview" | "profile" | "password" | "security";
type Profile = { email: string; full_name: string | null; phone: string | null; locale: string; email_notifications: boolean; security_notifications: boolean; created_at: string };
type Factor = { id: string; friendly_name?: string; status: string };
type Overview = { access: { trialStatus: string; trialEndsAt: string | null; subscriptionActive: boolean; hasAccess: boolean }; subscription: { status: string; currentPeriodEnd: string | null; billingMethod: string } | null; plan: { name: string; included_plays: number; storage_gb: number; prisma_ai_analyses: number; team_seats: number } | null; usage: { plays: number; storageBytes: number; videos: number; aiCredits: number; aiUsed: number } };

const tabs = [
  { id: "overview" as const, label: "Visão geral", icon: CircleUserRound },
  { id: "profile" as const, label: "Perfil e preferências", icon: User },
  { id: "password" as const, label: "Senha", icon: Lock },
  { id: "security" as const, label: "Segurança", icon: Shield },
];

export default function SettingsPage() {
  const [tab, setTab] = useState<Tab>("overview");
  const [profile, setProfile] = useState<Profile | null>(null);
  const [overview, setOverview] = useState<Overview | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([
    fetch("/api/account/profile", { cache: "no-store" }).then((response) => response.json()),
    fetch("/api/account/overview", { cache: "no-store" }).then((response) => response.json()),
  ]).then(([account, accountOverview]) => { setProfile(account.profile ?? null); setOverview(accountOverview.error ? null : accountOverview); }); }, []);

  return <><Header /><main className="dashboard-content flex-1">
    <div className="mb-7"><p className="text-[12px] font-semibold uppercase tracking-[.16em] text-prisma-blue">Central da conta</p><h1 className="mt-2 text-[30px] font-semibold tracking-[-.8px] themeable-text-ink">Configurações</h1><p className="mt-1 max-w-2xl text-[14px] themeable-text-ink-muted-48">Acompanhe sua capacidade, personalize sua conta e controle a segurança sem sair desta tela.</p></div>
    <div className="grid gap-6 xl:grid-cols-[230px_minmax(0,1fr)]">
      <nav className="h-fit rounded-[20px] border p-2 themeable-bg-canvas themeable-border-hairline xl:sticky xl:top-24">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => { setTab(item.id); setMessage(""); }} className={`flex min-h-12 w-full items-center gap-3 rounded-[14px] px-3 text-left text-[14px] transition ${tab === item.id ? "bg-prisma-blue text-white shadow-sm" : "themeable-text-ink hover:bg-prisma-blue/8"}`}><Icon size={18} />{item.label}<ChevronRight size={15} className="ml-auto opacity-50" /></button>; })}</nav>
      <div className="min-w-0">{message && <div role="status" className="mb-4 rounded-[14px] border border-prisma-blue/25 bg-prisma-blue/5 px-4 py-3 text-[13px] text-prisma-blue">{message}</div>}
        {tab === "overview" && <OverviewPanel overview={overview} profile={profile} />}
        {tab === "profile" && (profile ? <ProfilePanel key={profile.email} profile={profile} setProfile={setProfile} setMessage={setMessage} /> : <Skeleton />)}
        {tab === "password" && <PasswordPanel setMessage={setMessage} />}
        {tab === "security" && <SecurityPanel setMessage={setMessage} />}
      </div>
    </div>
  </main></>;
}

function OverviewPanel({ overview, profile }: { overview: Overview | null; profile: Profile | null }) {
  if (!overview) return <Skeleton />;
  const storageGb = overview.usage.storageBytes / 1024 ** 3;
  const plan = overview.plan;
  const playPercent = plan?.included_plays ? overview.usage.plays / plan.included_plays * 100 : 0;
  const storagePercent = plan?.storage_gb ? storageGb / plan.storage_gb * 100 : 0;
  return <div className="space-y-5">
    <section className="overflow-hidden rounded-[22px] border themeable-bg-canvas themeable-border-hairline"><div className="bg-gradient-to-br from-prisma-blue to-[#4b8fff] p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[12px] font-semibold uppercase tracking-[.14em] text-white/70">Sua operação</p><h2 className="mt-2 text-[25px] font-semibold">{profile?.full_name || "Conta Prisma"}</h2><p className="mt-1 text-[13px] text-white/75">{plan ? `${plan.name} ativo` : overview.access.trialStatus === "active" ? "Teste gratuito ativo" : "Escolha um plano para publicar"}</p></div><Link href="/dashboard/billing" className="rounded-full bg-white px-4 py-2.5 text-[13px] font-semibold text-prisma-blue">Gerenciar plano</Link></div></div>
      <div className="grid gap-px bg-black/5 sm:grid-cols-2 xl:grid-cols-4">{[
        { icon: Play, label: "Plays neste mês", value: overview.usage.plays.toLocaleString("pt-BR"), detail: plan ? `de ${plan.included_plays.toLocaleString("pt-BR")}` : "sem plano", percent: playPercent },
        { icon: HardDrive, label: "Biblioteca", value: `${storageGb.toLocaleString("pt-BR", { maximumFractionDigits: 2 })} GB`, detail: plan ? `de ${plan.storage_gb} GB` : `${overview.usage.videos} vídeos`, percent: storagePercent },
        { icon: Sparkles, label: "Créditos Prisma IA", value: overview.usage.aiCredits.toLocaleString("pt-BR"), detail: `${overview.usage.aiUsed} utilizados`, percent: 0 },
        { icon: Database, label: "VSLs na conta", value: overview.usage.videos.toLocaleString("pt-BR"), detail: "organizadas na biblioteca", percent: 0 },
      ].map((item) => { const Icon = item.icon; return <article key={item.label} className="themeable-bg-canvas p-5"><div className="flex items-center gap-2 text-prisma-blue"><Icon size={17} /><span className="text-[12px] font-medium themeable-text-ink-muted-48">{item.label}</span></div><strong className="mt-3 block text-[25px] tracking-[-.4px] themeable-text-ink">{item.value}</strong><p className="mt-1 text-[12px] themeable-text-ink-muted-48">{item.detail}</p>{item.percent > 0 && <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-black/8 dark:bg-white/10"><div className={`h-full rounded-full ${item.percent >= 90 ? "bg-amber-500" : "bg-prisma-blue"}`} style={{ width: `${Math.min(item.percent, 100)}%` }} /></div>}</article>; })}</div>
    </section>
    <div className="grid gap-5 lg:grid-cols-2"><Card title="Acesso e cobrança" description="Status atual da assinatura e do período de acesso."><div className="space-y-3"><Info icon={CreditCard} title={plan?.name ?? "Sem assinatura"} detail={overview.subscription?.currentPeriodEnd ? `Válido até ${new Date(overview.subscription.currentPeriodEnd).toLocaleDateString("pt-BR")}` : overview.access.trialEndsAt ? `Teste até ${new Date(overview.access.trialEndsAt).toLocaleDateString("pt-BR")}` : "Ative o teste ou escolha um plano"} /><Info icon={Sparkles} title="Prisma IA" detail={`${overview.usage.aiCredits} créditos disponíveis para análises`} /></div></Card><Card title="Proteção da conta" description="Resumo das camadas que protegem sua operação."><div className="space-y-3"><Info icon={Shield} title="Sessão protegida" detail="Autenticação e cookies seguros do Supabase" /><Info icon={Bell} title="Alertas de segurança" detail={profile?.security_notifications ? "Ativados" : "Desativados nas preferências"} /></div></Card></div>
  </div>;
}

function Card({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-[20px] border themeable-bg-canvas themeable-border-hairline"><div className="border-b px-5 py-4 themeable-border-hairline"><h2 className="text-[17px] font-semibold themeable-text-ink">{title}</h2>{description && <p className="mt-1 text-[13px] themeable-text-ink-muted-48">{description}</p>}</div><div className="p-5">{children}</div></section>; }
function Skeleton() { return <div className="grid min-h-72 animate-pulse place-items-center rounded-[20px] border themeable-bg-canvas themeable-border-hairline"><p className="text-[14px] themeable-text-ink-muted-48">Carregando sua conta…</p></div>; }
function Info({ icon: Icon, title, detail }: { icon: typeof Shield; title: string; detail: string }) { return <div className="flex gap-3 rounded-[14px] border p-4 themeable-border-hairline"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-[10px] bg-prisma-blue/10 text-prisma-blue"><Icon size={18} /></span><div><p className="text-[14px] font-medium themeable-text-ink">{title}</p><p className="mt-1 text-[12px] themeable-text-ink-muted-48">{detail}</p></div></div>; }
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="mt-2 h-11 w-full rounded-[13px] border bg-transparent px-4 text-[14px] outline-none themeable-border-hairline themeable-text-ink focus:border-prisma-blue" />; }
function Toggle({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={`h-6 w-11 rounded-full p-1 transition ${checked ? "bg-prisma-blue" : "bg-black/20 dark:bg-white/20"}`}><span className={`block h-4 w-4 rounded-full bg-white transition-transform ${checked ? "translate-x-5" : ""}`} /></button>; }

function ProfilePanel({ profile, setProfile, setMessage }: { profile: Profile; setProfile: (profile: Profile) => void; setMessage: (value: string) => void }) {
  const [name, setName] = useState(profile.full_name ?? ""), [phone, setPhone] = useState(profile.phone ?? ""), [locale, setLocale] = useState(profile.locale), [emailNotifications, setEmailNotifications] = useState(profile.email_notifications), [securityNotifications, setSecurityNotifications] = useState(profile.security_notifications);
  async function save() { const response = await fetch("/api/account/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ fullName: name, phone, locale, emailNotifications, securityNotifications }) }); const data = await response.json(); if (response.ok) { setProfile(data.profile); setMessage("Perfil e preferências atualizados."); } else setMessage("Não foi possível atualizar o perfil."); }
  return <div className="space-y-5"><Card title="Dados pessoais" description="Informações usadas na sua conta e nos checkouts."><div className="grid gap-5 sm:grid-cols-2"><label className="text-[13px] font-medium themeable-text-ink">Nome completo<Input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-[13px] font-medium themeable-text-ink">Telefone<Input value={phone} onChange={(event) => setPhone(event.target.value)} /></label><label className="text-[13px] font-medium themeable-text-ink">E-mail<Input value={profile.email} readOnly /></label><label className="text-[13px] font-medium themeable-text-ink">Idioma<select value={locale} onChange={(event) => setLocale(event.target.value)} className="mt-2 h-11 w-full rounded-[13px] border bg-transparent px-4 themeable-border-hairline themeable-text-ink"><option value="pt-BR">Português</option><option value="es">Español</option><option value="en">English</option></select></label></div></Card><Card title="Notificações" description="Escolha como deseja receber informações importantes."><div className="space-y-3"><Preference icon={Bell} title="E-mails do produto" detail="Processamento, limites e novidades" checked={emailNotifications} onChange={setEmailNotifications} /><Preference icon={Shield} title="Alertas de segurança" detail="Senha, MFA e acessos importantes" checked={securityNotifications} onChange={setSecurityNotifications} /></div><button onClick={save} className="mt-5 min-h-11 rounded-full bg-prisma-blue px-5 text-[14px] font-medium text-white">Salvar alterações</button></Card></div>;
}
function Preference({ icon: Icon, title, detail, checked, onChange }: { icon: typeof Bell; title: string; detail: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 rounded-[14px] border p-4 themeable-border-hairline"><div className="flex gap-3"><Icon size={18} className="mt-0.5 text-prisma-blue" /><div><p className="text-[14px] font-medium themeable-text-ink">{title}</p><p className="text-[12px] themeable-text-ink-muted-48">{detail}</p></div></div><Toggle checked={checked} onChange={onChange} /></div>; }

function PasswordPanel({ setMessage }: { setMessage: (value: string) => void }) { const [password, setPassword] = useState(""), [confirm, setConfirm] = useState(""); async function update() { if (password !== confirm) return setMessage("As senhas não coincidem."); const response = await fetch("/api/account/password", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); setMessage(response.ok ? "Senha atualizada com sucesso." : "Use pelo menos 10 caracteres, com letras e números."); if (response.ok) { setPassword(""); setConfirm(""); } } return <Card title="Alterar senha" description="A senha é processada pelo Supabase Auth e nunca é armazenada pela Prisma."><div className="grid gap-5 sm:grid-cols-2"><label className="text-[13px] font-medium themeable-text-ink">Nova senha<Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></label><label className="text-[13px] font-medium themeable-text-ink">Confirmar senha<Input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" /></label></div><div className="mt-4 flex flex-wrap gap-4 text-[12px] themeable-text-ink-muted-48"><span className="flex gap-1"><CheckCircle2 size={15} />10 caracteres</span><span className="flex gap-1"><CheckCircle2 size={15} />Letras e números</span></div><button onClick={update} disabled={!password || !confirm} className="mt-5 min-h-11 rounded-full bg-prisma-blue px-5 text-[14px] text-white disabled:opacity-40">Atualizar senha</button></Card>; }

function SecurityPanel({ setMessage }: { setMessage: (value: string) => void }) { const [factors, setFactors] = useState<Factor[]>([]), [qr, setQr] = useState(""), [factorId, setFactorId] = useState(""), [code, setCode] = useState(""); useEffect(() => { void fetch("/api/account/security", { cache: "no-store" }).then((response) => response.json()).then((data) => setFactors(data.factors ?? [])); }, []); async function enroll() { const { data, error } = await createClient().auth.mfa.enroll({ factorType: "totp", friendlyName: "Prisma Player" }); if (error) return setMessage("Não foi possível iniciar o MFA."); setFactorId(data.id); setQr(data.totp.qr_code); } async function verify() { const supabase = createClient(); const challenge = await supabase.auth.mfa.challenge({ factorId }); if (challenge.error) return setMessage("Falha ao criar o desafio MFA."); const result = await supabase.auth.mfa.verify({ factorId, challengeId: challenge.data.id, code }); setMessage(result.error ? "Código inválido." : "Autenticação em dois fatores ativada."); if (!result.error) { setQr(""); setCode(""); const listed = await supabase.auth.mfa.listFactors(); setFactors(listed.data?.all ?? []); } } return <div className="space-y-5"><Card title="Autenticação em dois fatores" description="Proteja sua operação com um aplicativo autenticador TOTP.">{factors.some((factor) => factor.status === "verified") ? <div className="flex items-center gap-3 rounded-[14px] border border-green-500/25 bg-green-500/5 p-4 text-[14px] text-green-600"><Shield size={20} />MFA ativo nesta conta</div> : qr ? <div className="grid gap-5 sm:grid-cols-[180px_1fr]"><div dangerouslySetInnerHTML={{ __html: qr }} className="overflow-hidden rounded-[14px] bg-white p-3" /><div><label className="text-[13px] font-medium themeable-text-ink">Código de 6 dígitos<Input value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" /></label><button onClick={verify} disabled={code.length !== 6} className="mt-4 min-h-11 rounded-full bg-prisma-blue px-5 text-white disabled:opacity-40">Confirmar e ativar</button></div></div> : <button onClick={enroll} className="flex min-h-11 items-center gap-2 rounded-full bg-prisma-blue px-5 text-[14px] text-white"><Smartphone size={17} />Configurar aplicativo</button>}</Card><Card title="Sessão e privacidade"><div className="space-y-3"><Info icon={KeyRound} title="Cookie HttpOnly" detail="Tokens de sessão não ficam acessíveis ao JavaScript da página" /><Info icon={Shield} title="Dados isolados" detail="RLS impede acesso aos vídeos e métricas de outras contas" /></div></Card></div>; }
